updating tagoio sdk
tago-io/analysis-example-deviceoffline pull request #4
Opened 2023-07-11 11:51 UTC by rafaelTelesS

## What does PR do?

The TagoIO Sdk has been updated to work with the new access rule system for analysis. This system allows you to control who can access your analysis, what actions they can perform, and under what conditions. To use the new system, you need to update your Sdk version and follow the documentation on how to create and manage access rules. 

## Type of alteration

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [x] Documentation update

2023-07-11 17:26 UTC, Freddyminu requested changes

2023-07-11 17:26 UTC, Freddyminu commented on README.md
>  after that, you can run the project just calling analysis, `node analysis.js`;
Run it locally, you should have lastest node version and install all the dependencies by running `npm install` in your terminal in the project's directory,
after that, you can run the project by calling the analysis, `node analysis.js`;

2023-07-11 17:26 UTC, Freddyminu commented on README.md
> +## What this does
## What the analysis does

2023-07-11 17:26 UTC, Freddyminu commented on README.md
> +This analysis must run by Time Interval. It checks if devices with given Tags had communication in the past minutes. If not, it sends an email or sms alert.
This analysis must run by triggered by a [Time Interval](https://help.tago.io/portal/en/kb/articles/244-trigger-by-schedule). It checks whether devices with given Tags checked in, in the past minutes. If not, it sends an email or sms alert.

2023-07-11 17:26 UTC, Freddyminu commented on README.md
> +## How to use on TagoIO
## How to use this analysis internally at TagoIO servers

2023-07-11 17:26 UTC, Freddyminu commented on README.md
> +    5 - sms_list: Phone number list comma separated. The phone number must include the country code
5 - sms_list: Phone number list comma separated. The phone number must include the country code.

2023-07-11 17:26 UTC, Freddyminu commented on README.md
> +   1 - Click the button "Add Policy" at this url: https://admin.tago.io/am;
1 - Click the button "[Add Policy](https://admin.tago.io/am)".

2023-07-11 17:26 UTC, Freddyminu commented on README.md
> +   2 - In the Target selector, select the Analysis with the field set as "ID" and choose your Analysis in the list;
2 - In the Target selector, with the field set as "ID", choose your Analysis in the list;

2023-07-11 17:26 UTC, Freddyminu commented on analysis.js
> + **  2 - In the Target selector, select the Analysis with the field set as "ID" and choose your Analysis in the list;
** 2 - In the Target selector, with the field set as "ID", choose your Analysis in the list;

2023-09-01 08:42 UTC, vitorfdl approved these changes

2023-09-01 08:42 UTC, merged